name: run main.py

#on:
#  schedule:
#    - cron: '0 7 * * *'
#    - cron: "*/1 * * * *"

on:
  push:
    branches:
      - main

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: cache poetry install
        uses: actions/cache@v2
        with:
          path: ~/.local
          key: poetry-1.1.12-0

      - name: cache deps
        id: cache-deps
        uses: actions/cache@v2
        with:
          path: .venv
          key: pydeps-${{ hashFiles('**/poetry.lock') }}

      - run: poetry install --no-interaction --no-root
        if: steps.cache-deps.outputs.cache-hit != 'true'

      - name: execute py script # run main.py
        env:
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        run: python main.py